Events: posts, terms
insideout10/wordlift-plugin pull request #1701
Opened 2023-07-19 16:43 UTC by mykytadudariev

2023-07-20 12:33 UTC, ziodave requested changes
All the new code that you wrote must be moved to a module in src/modules/events

2023-07-20 12:33 UTC, ziodave commented on src/classes/vocabulary/jsonld/class-post-jsonld.php
> +			if ( ! empty( $data[ $key ] ) ) {
I think we're missing a case:

1. I have x mentions
2. Event has been sent
3. x mentions recorded in post meta
4. Now mentions is not present anymore (i.e. `empty( $data[ $key ] ) === true`)
5. You should send a count of mentions = 0, the current code won't process it

Same happens later for terms

2023-07-20 12:33 UTC, ziodave commented on src/classes/vocabulary/jsonld/class-term-jsonld.php
> +			if ( ! empty( $data[ $key ] ) ) {
Same as https://github.com/insideout10/wordlift-plugin/pull/1701/files?diff=unified&w=1#diff-bc6fb5d934e6959cc998029202a88d82ec03220e8b5bc8cacd773c34c76ac54bR189

2023-07-20 12:33 UTC, ziodave commented on src/classes/vocabulary/jsonld/class-post-jsonld.php
> +		if ( Jsonld_Context_Enum::PAGE !== $context || empty( $jsonld_arr[0] ) ) {
If the array is empty, but before we sent a count of mentions and about then we should send an updated count of 0 for both.

2023-07-20 12:33 UTC, ziodave commented on src/classes/vocabulary/jsonld/class-term-jsonld.php
> +		return get_term_link( $id );
We should really get the current page here, I am not sure what's happening here?

2023-07-23 11:45 UTC, ziodave requested changes

2023-07-24 08:35 UTC, mykytadudariev commented on src/modules/events/includes/Options_Entity/Events_Options_Entity_Include_Exclude.php
> +	public function __construct( Api_Service $api_service ) {
Sure, no problem, I just copied that "logic" from an existing module [Food Kg](https://github.com/insideout10/wordlift-plugin/blob/main/src/modules/food-kg/includes/Main_Entity/Food_Kg_Main_Entity_Runner.php#L28). I mean the same "behavior"

2023-07-24 08:38 UTC, mykytadudariev commented on src/modules/events/includes/Options_Entity/Events_Options_Entity_Include_Exclude.php
> +		$old_config = get_option( 'wl_exclude_include_urls_settings_old', array() );
ok, no problem, I did this logic due to your requirements with `add_action( 'update_option_wl_exclude_include_urls_settings', ... )` like in the document. But no problem, let's rebuild that with another hook

2023-07-26 10:36 UTC, merged